### ISSUE TITLE
smaller stack

### ISSUE THREAD

**Issue by gralewski** [DellAquila/SatisfactoryModding_DellAquila#1]
Hey Andre, i find this mod very useful, but stack 500 with stack multiplying mods is just too big a numer in my opinion.
Assuming that stack packing is useful mostly for belt compression, stack like 5 would be best, because machines will stop sucking all the items and starving these placed further in the belt path.

Currently in my world one packing machine is filled with 2000 packed iron ore stacks which equals 100.000 unpacked iron ore.
It's far too much. Can you add configurable stacks, for example like in "Stack Overload" mod?

**Comment by gralewski** [comment]
ping :)

**Comment by yeetmanthecoolman** [comment]
i agree. mabye we should be able to pack power shards and stuff too?
